version: '3.7'

services:
  api:
    image: llasapg/rabbit-banking-api:latest
    restart: always
    ports:
      - "9000:9000"
      - "8088:8088"
  bankingssql:
    image: mysql:8.0.17
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
    ports:
    - "3309:3306"
